preload = /home/smule/Pictures/wallpapers/Buildings.png
preload = /home/smule/Pictures/wallpapers/Beach_light.png

wallpaper = desc:AOC 2460G5 GKAH9HA054523,/home/smule/Pictures/wallpapers/Buildings.png
wallpaper = desc:AOC 32G1WG4 0x000031C6,/home/smule/Pictures/wallpapers/Beach_light.png

splash = false
