wallpaper {
    monitor = DP-2
    path = /home/smule/Pictures/wallpapers/swordfish.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/smule/Pictures/wallpapers/swordfish.jpg
    fit_mode = cover
}
