$configs = $HOME/.config/hypr/configs
$scripts = $HOME/.config/hypr/scripts

source=$configs/autostart.conf
source=$configs/env.conf
source=$configs/input.conf
source=$configs/keybinds.conf
source=$configs/monitors.conf
source=$configs/settings.conf
source=$configs/windowrules.conf
